# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160304_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdatedDate', models.DateTimeField(auto_now=True, null=True)),
                ('Code', models.CharField(max_length=100)),
                ('CodeType', models.CharField(max_length=50)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Client')),
                ('CreatedByUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_clientcode_CreatedByUser', to='main.Authentication')),
                ('UpdatedByUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_clientcode_UpdatedByUser', to='main.Authentication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
                ('Subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subscription')),
            ],
        ),
        migrations.AlterField(
            model_name='seal',
            name='CreatedByUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_seal_CreatedByUser', to='main.Authentication'),
        ),
        migrations.AlterField(
            model_name='seal',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='seal',
            name='UpdatedByUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_seal_UpdatedByUser', to='main.Authentication'),
        ),
        migrations.AlterField(
            model_name='seal',
            name='UpdatedDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
