# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160304_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authentication',
            options={'verbose_name': 'user'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'currencies'},
        ),
        migrations.AlterModelOptions(
            name='security',
            options={'verbose_name_plural': 'security filings'},
        ),
    ]
