# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160304_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='Mode',
            field=models.CharField(choices=[('A', 'Air'), ('O', 'Ocean'), ('R', 'Rail'), ('T', 'Truck')], default='O', max_length=1),
        ),
    ]
