# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_eventgroup_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Type',
            field=models.CharField(blank=True, choices=[('w', 'Warehouse'), ('o', 'Office'), ('c', 'Container Yard'), (None, '')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='AgentModes',
            field=models.CharField(blank=True, choices=[('w', 'Warehouser'), ('t', 'Trucker'), ('s', 'Shipper?'), ('c', 'Consignee?'), ('n', 'NVO'), ('m', 'MVO'), ('r', 'Rail'), (None, '')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='Order',
            field=models.IntegerField(default=1),
        ),
    ]
