# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160308_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication',
            name='CreatedByUser',
        ),
    ]
