# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160308_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='PostalZipCode',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='city',
            name='StateRegionName',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='security',
            name='OriginalAcceptedDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='OriginalSentDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='ParentBillNumberPrefix',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Consigee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Consigee', to='main.Address'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='ConsigneeName',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Notify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notify', to='main.Address'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Notify2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notify2', to='main.Address'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Notify2Name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='NotifyName',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Shipper', to='main.Address'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='ShipperName',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
