# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160308_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ActualDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Contact'),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.EventGroup'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ScheduledDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
