# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20160308_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='CreatedByUser',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='CreatedDate',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='UpdatedByUser',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='UpdatedDate',
        ),
        migrations.AddField(
            model_name='detail',
            name='CountryOfOrigin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Country'),
        ),
        migrations.AddField(
            model_name='detail',
            name='HarmonizedTariffNumber',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='OriginalAcceptedDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='OriginalSentDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
