# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20160309_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detail',
            name='StockKeepingUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.StockKeepingUnit'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Weight',
            field=models.IntegerField(default=0),
        ),
    ]
