# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 01:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20160309_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='Consigee',
            new_name='Consignee',
        ),
        migrations.AddField(
            model_name='detail',
            name='CreatedByUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='main_detail_CreatedByUser', to='main.Authentication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 10, 1, 37, 4, 165769, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='UpdatedByUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_detail_UpdatedByUser', to='main.Authentication'),
        ),
        migrations.AddField(
            model_name='detail',
            name='UpdatedDate',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 10, 1, 37, 17, 704599, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockkeepingunit',
            name='CountryOfOrigin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Country'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='Address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Address'),
        ),
        migrations.AlterField(
            model_name='containerdetail',
            name='CreatedByUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_containerdetail_CreatedByUser', to='main.Authentication'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ActualDate',
            field=models.DateTimeField(blank=True, default='0000-00-00 00:00:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ScheduledDate',
            field=models.DateTimeField(blank=True, default='0000-00-00 00:00:00'),
        ),
        migrations.AlterField(
            model_name='security',
            name='OriginalAcceptedDate',
            field=models.DateTimeField(blank=True, default='0000-00-00 00:00:00'),
        ),
        migrations.AlterField(
            model_name='security',
            name='OriginalSentDate',
            field=models.DateTimeField(blank=True, default='0000-00-00 00:00:00'),
        ),
        migrations.AlterField(
            model_name='stockkeepingunit',
            name='CreatedByUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_stockkeepingunit_CreatedByUser', to='main.Authentication'),
        ),
        migrations.AlterField(
            model_name='stockkeepingunit',
            name='UpdatedByUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_stockkeepingunit_UpdatedByUser', to='main.Authentication'),
        ),
    ]
